title: "Название вашего сайта"
description: "Описание сайта"
baseurl: "" # Оставьте пустым для основного домена
url: "https://itsvakonst.github.io"

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
